version: '3.4'

services:
  identity.webui:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    networks:
      - identity-network

  identity.db:
    environment:
      MYSQL_DATABASE: 'identity_db'
      MYSQL_USER: 'dbuser'  
      MYSQL_PASSWORD: 'dbpassword' 
      MYSQL_ROOT_PASSWORD: 'dbrootpassword' 
    ports:
      - "3307:3306"  
    volumes:
      - identity.db-data:/var/lib/mysql 
    networks:
      - identity-network

volumes:
  identity.db-data:
networks:
  identity-network: