version: '3.4'

services:
  identity.webui:
    image: ${DOCKER_REGISTRY-}identitywebui
    container_name: identity-microservice
    build:
      context: .
      dockerfile: Identity.WebUI/Dockerfile
    depends_on:
      - identity.db

  identity.db:
    image: mysql:8.3.0
    container_name: identity-db