version: '3.4'

services:
  identity.webui:
    image: ${DOCKER_REGISTRY-}identitywebui
    container_name: identity-microservice
    build:
      context: .
      dockerfile: Identity.WebUI/Dockerfile
    depends_on:
      - identity.db
      - elasticsearch 
    
  identity.db:
    image: mysql:8.3.0
    container_name: identity-db

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.1
    container_name: elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.1
    container_name: kibana
    depends_on:
      - elasticsearch